language: c

compiler:
    - clang
    - gcc

before_script:
    - sudo apt-get update
    - sudo apt-get install -qq libfuse-dev libpolarssl-dev

script: cd src && make

after_script: ./dislocker --help

notifications:
    email:
        recipients:
            - aorimn@gmail.com

        on_success: always
        on_failure: always
