language: c

compiler:
    - clang
    - gcc

os:
    - linux
    - osx

install:
    - cmake .
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make travis-install-linux; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make travis-install-osx; fi
    - make
    - sudo make install

script:
    - make travis-test

notifications:
    email:
        recipients:
            - aorimn@gmail.com

        on_success: always
        on_failure: always
