language: c

compiler:
    - clang
    - gcc

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libfuse-dev libpolarssl-dev

before_script:
    - cd src

script:
    - make CC=$CC
    - make install
    - dislocker --help

notifications:
    email:
        recipients:
            - aorimn@gmail.com

        on_success: always
        on_failure: always
