language: c

compiler:
    - clang
    - gcc

os:
    - linux
    - osx

before_install:
    - cd src

install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make travis-install-linux; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make CC=$(CC); fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make travis-install-osx; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make CC=$(CC) SSLIB=mbedtls; fi
    - sudo make CC=$(CC) install

script:
    - make travis-test

notifications:
    email:
        recipients:
            - aorimn@gmail.com

        on_success: always
        on_failure: always
