language: c

compiler:
    - clang
    - gcc

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libfuse-dev libpolarssl-dev

script: cd src && make CC=$CC && LD_LIBRARY_PATH=`pwd` ./dislocker --help

notifications:
    email:
        recipients:
            - aorimn@gmail.com

        on_success: always
        on_failure: always
